"""Add additional patient fields gender address ssn insurance medical_history

Revision ID: 8d555c9f8910
Revises: 2b3198eaf726
Create Date: 2025-11-06 12:22:38.253562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d555c9f8910'
down_revision = '2b3198eaf726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('ssn', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('insurance_number', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('medical_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'medical_history')
    op.drop_column('patients', 'insurance_number')
    op.drop_column('patients', 'ssn')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###

