"""Add financial management models

Revision ID: 7df0a05fa9b2
Revises: 75281a63a045
Create Date: 2025-11-07 22:33:29.857152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df0a05fa9b2'
down_revision = '75281a63a045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_contact', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=True)
    op.create_table('bir_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_period_start', sa.Date(), nullable=False),
    sa.Column('report_period_end', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('withholding_tax', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bir_reports_id'), 'bir_reports', ['id'], unique=False)
    op.create_table('doctor_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_number', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=200), nullable=False),
    sa.Column('doctor_license', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('withholding_tax', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='doctorpayoutstatus'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_payouts_id'), 'doctor_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_payouts_payout_number'), 'doctor_payouts', ['payout_number'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('PHARMACY', 'MEDICAL_SUPPLIES', 'SALARIES', 'UTILITIES', 'RENT', 'EQUIPMENT', 'MAINTENANCE', 'MARKETING', 'PROFESSIONAL_FEES', 'TAXES', 'INSURANCE', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('vendor_tin', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('is_vat_inclusive', sa.Integer(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    # SQLite doesn't support ALTER COLUMN, skipping these changes
    # op.alter_column('invoice_items', 'category',
    #            existing_type=sa.VARCHAR(length=50),
    #            server_default=None,
    #            type_=sa.Enum('PROFESSIONAL_FEE', 'LABORATORY', 'MEDICATION', 'ROOM_CHARGE', 'PROCEDURE', 'SUPPLIES', 'OTHER', name='itemcategory'),
    #            existing_nullable=False)
    # op.alter_column('invoices', 'philhealth_coverage',
    #            existing_type=sa.FLOAT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('invoices', 'hmo_coverage',
    #            existing_type=sa.FLOAT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('invoices', 'senior_pwd_discount',
    #            existing_type=sa.FLOAT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('invoices', 'patient_balance',
    #            existing_type=sa.FLOAT(),
    #            server_default=None,
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'patient_balance',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               existing_nullable=False)
    op.alter_column('invoices', 'senior_pwd_discount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               existing_nullable=False)
    op.alter_column('invoices', 'hmo_coverage',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               existing_nullable=False)
    op.alter_column('invoices', 'philhealth_coverage',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               existing_nullable=False)
    op.alter_column('invoice_items', 'category',
               existing_type=sa.Enum('PROFESSIONAL_FEE', 'LABORATORY', 'MEDICATION', 'ROOM_CHARGE', 'PROCEDURE', 'SUPPLIES', 'OTHER', name='itemcategory'),
               server_default=sa.text("'other'"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_doctor_payouts_payout_number'), table_name='doctor_payouts')
    op.drop_index(op.f('ix_doctor_payouts_id'), table_name='doctor_payouts')
    op.drop_table('doctor_payouts')
    op.drop_index(op.f('ix_bir_reports_id'), table_name='bir_reports')
    op.drop_table('bir_reports')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###

