"""Add security fields to User model (RBAC, account lockout, password expiry)

Revision ID: 4be5868a916d
Revises: 7df0a05fa9b2
Create Date: 2025-11-10 10:13:38.879944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be5868a916d'
down_revision = '7df0a05fa9b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip ALTER COLUMN for SQLite - not supported
    # op.alter_column('invoice_items', 'category', ...)
    # op.alter_column('invoices', 'philhealth_coverage', ...)
    # op.alter_column('invoices', 'hmo_coverage', ...)
    # op.alter_column('invoices', 'senior_pwd_discount', ...)
    # op.alter_column('invoices', 'patient_balance', ...)

    # Add new security fields to users table
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'is_active')
    # Skip ALTER COLUMN for SQLite - not supported
    # ### end Alembic commands ###

